name: Download Athenry Weather

on:
    schedule:
        - cron: "15 20 * * *" # Runs daily at 8.15pm.
    workflow_dispatch: # Allows manual running of workflow.

permissions:
    contents: write

jobs:
    dowload_weather:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the repository.
            - name: Check out repository
              uses: actions/checkout@v4

            # Step 2: Set up execution permissions.
            - name: Make file executable
              run: chmod +x weather.sh

            # Step 3: Run weather.sh script.
            - name: Run weather script
              run: ./weather.sh

            # Step 4: Commit and push the changes
            - name: Commit and push changes
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "githum-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Adding today's weather."
                git push